resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
  instances:
    loanService:
      baseConfig: default
      waitDurationInOpenState: 5000

resilience4j.retry:
  instances:
    loanService:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2

resilience4j.bulkhead:
  instances:
    loanService:
      maxConcurrentCalls: 10

resilience4j.thread-pool-bulkhead:
  instances:
    loanService:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1

resilience4j.ratelimiter:
  instances:
    loanService:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100

resilience4j.timelimiter:
  instances:
    loanService:
      timeoutDuration: 2s
      cancelRunningFuture: true
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        slidingWindowSize: 100
#        permittedNumberOfCallsInHalfOpenState: 10
#        waitDurationInOpenState: 10000
#        failureRateThreshold: 60
#        eventConsumerBufferSize: 10
#        registerHealthIndicator: true
#    instances:
#      loanService:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        waitDurationInOpenState: 5s
#        slidingWindowType: COUNT_BASED


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always